AUTHOR := hmartzol
NAME := ../ft_nm
EXEARGS :=
SRCDIR := src
INCDIRS := inc
OBJDIR := .obj
DEPDIR := .dep
MAIN := main.c
ITEMS :=
CFLAGS := -Wall -Wextra -Werror
PINC := ../libft/inc
CLIB := ../libft
LIB := ../libft/libft.a
LARGS :=
include ../Makefiles/Makefile.gen
